version: '3'

services:
  shadownet-db:
    container_name: shadownet-db
    restart: always
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - shadownet_postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432

  shadownet-api:
    container_name: shadownet-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - shadownet-db
    environment:
      ConnectionStrings__DefaultConnection: host=shadownet-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    ports:
      - 0.0.0.0:5010:5000

  shadownet-sync:
    container_name: shadownet-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=shadownet-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5001
      TezosNode__Endpoint: https://rpc.tzkt.io/shadownet/
    depends_on:
      - shadownet-db
    ports:
      - 0.0.0.0:5011:5001

volumes:
  shadownet_postgres:
